
# Board settings.
#BOARD = atmega328

#PORT = /dev/ttyUSB1

LIB_DIRS = ../../libs/vs1063 ../../libs/SdFat ../../libs/IRremote /usr/share/arduino-100/libraries/SPI/ /usr/share/arduino-100/libraries/Wire/ /usr/share/arduino-100/libraries/Wire/utility/

include ../Makefile.master

