
# Board settings.
#BOARD = atmega328

#PORT = /dev/ttyUSB1

LIB_DIRS = /home/prodan/_work/arduino/libs/vs1063 /home/prodan/_work/arduino/libs/SdFat /home/prodan/_work/arduino/libs/IRremote /usr/share/arduino-100/libraries/SPI/ /usr/share/arduino-100/libraries/Wire/ /usr/share/arduino-100/libraries/Wire/utility/

include ../Makefile.master

